# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-14 13:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.CharField(max_length=250, verbose_name='текст ответа')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='наименование')),
                ('text', models.CharField(max_length=250, verbose_name='текст опроса')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='время публикации')),
                ('date_start', models.DateTimeField(verbose_name='опрос активен после')),
                ('date_end', models.DateTimeField(verbose_name='опрос активен до')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='создатель опроса')),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='polls.Answer', verbose_name='выбранный ответ')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='polls.Question', verbose_name='ответ к опросу')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='polls.Question', verbose_name='опрос'),
        ),
    ]
